services:
  nginx:
    image: nginx:1.19.7
    container_name: bills-nginx
    restart: unless-stopped
    ports:
      - "8089:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - bills

  php:
    build:
      context: docker
      dockerfile: Dockerfile
    container_name: bills-php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html:cached
    networks:
      - bills

  composer:
    image: composer:2.5.7
    container_name: bills-composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - bills

  node:
    image: node:19.9
    container_name: bills-node
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - bills

networks:
  bills:
    driver: bridge
